DROP TABLE IF EXISTS "PSC"."USER";

CREATE TABLE "PSC"."USER"
(
    "ID" NUMBER NOT NULL,
    "NAME" NVARCHAR(32) NOT NULL,
    "PASSWORD" NVARCHAR(16) NOT NULL,
    "PHONE" NVARCHAR(11) NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NOT NULL,
    "DELETED" TINYINT NOT NULL,
    CONSTRAINT "PK_USER" NOT CLUSTER PRIMARY KEY("ID")
);

INSERT INTO "PSC"."USER" ("ID", "NAME", "PASSWORD", "PHONE", "CREATE_TIME", "UPDATE_TIME", "DELETED") VALUES (1, 'zhangsan', '123456', '13912345678', now(), now(), 0);
INSERT INTO "PSC"."USER" ("ID", "NAME", "PASSWORD", "PHONE", "CREATE_TIME", "UPDATE_TIME", "DELETED") VALUES (2, 'lisi', '123456', '13912345678', now(), now(), 0);


DROP TABLE IF EXISTS "PSC"."CAT";

CREATE TABLE "PSC"."CAT"
(
    "ID" NUMBER NOT NULL,
    "user_id" NUMBER NOT NULL,
    "NAME" NVARCHAR(32) NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NOT NULL,
    "DELETED" TINYINT NOT NULL,
    CONSTRAINT "PK_CAT" NOT CLUSTER PRIMARY KEY("ID")
);

INSERT INTO "PSC"."CAT" ("ID", "user_id", "NAME", "CREATE_TIME", "UPDATE_TIME", "DELETED") VALUES (1, 2, 'zs1', now(), now(), 0);
INSERT INTO "PSC"."CAT" ("ID", "user_id", "NAME", "CREATE_TIME", "UPDATE_TIME", "DELETED") VALUES (2, 1, 'zs2', now(), now(), 0);
INSERT INTO "PSC"."CAT" ("ID", "user_id", "NAME", "CREATE_TIME", "UPDATE_TIME", "DELETED") VALUES (3, 2, 'zs1', now(), now(), 0);
INSERT INTO "PSC"."CAT" ("ID", "user_id", "NAME", "CREATE_TIME", "UPDATE_TIME", "DELETED") VALUES (4, 2, 'ls2', now(), now(), 0);