server:
  port: 9050
spring:
  tomcat:
    max-threads: 5000
    max-connections: 20000
  datasource:
    url: jdbc:mysql://47.99.132.168:18009/practice?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: jjjHsGTbqJc5C123
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 1000
    test-on-borrow: true
    test-on-return: true
    time-between-eviction-runs-millis: 1800000
    num-tests-per-eviction-run: 3
    min-evictable-idle-time-millis: 1800000
    validation-query: SELECT 1
  jpa:
    database: MYSQL
    show-sql: true # Show or not log for each sql query
    hibernate:
      ddl-auto: update # Hibernate ddl auto : create, create-drop, update, validate, none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy # Naming strategy
    properties:
      hibernate:
        format_sql: true
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl