server:
  port: 9050
spring:
  tomcat:
    max-threads: 5000
    max-connections: 20000
  datasource:
    url: jdbc:mysql://47.99.132.168:18001/practice?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: jRtHsGTbqJc5C8Ye
    driverClassName: com.mysql.jdbc.Driver
    max-active: 1000
    test-on-borrow: true
    test-on-return: true
    time-between-eviction-runs-millis: 1800000
    num-tests-per-eviction-run: 3
    min-evictable-idle-time-millis: 1800000
    validation-query: SELECT 1
  jpa:
    database: MYSQL
    show-sql: true # Show or not log for each sql query
    hibernate:
      ddl-auto: update # Hibernate ddl auto : create, create-drop, update, validate, none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy # Naming strategy
    properties:
      hibernate:
        dialect: io.qiya.taihang.framework.config.LocalMySQL5Dialect  # stripped before adding them to the entity manager
        format_sql: true